### PR TITLE
Adding decommission announcement

### PR DESCRIPTION
**Pull request by gustavo-salazar**
Adding the announcement in the pfam home page:

Screenshot 2022-08-08 at 11 47 43

### CODE REVIEW

**Review by matthiasblum — CHANGES_REQUESTED** [review]
Looks good for the home page. Could you uncomment `PfamWeb/root/components/sitewide_warning.html` and add a short message so a warning is displayed on all pages?

**Comment by gustavo-salazar** [comment]
Mhh... I didn't notice that component, should we move the whole message there intead?

**Comment by matthiasblum** [comment]
There is a component for the home page: `PfamWeb/root/components/homepage_warning.html`. You could move the message there (with links to InterPro, blog post, etc.). But we can also show a warning on every page using `PfamWeb/root/components/sitewide_warning.html` (assuming it's just a small banner).

**Comment by gustavo-salazar** [comment]
Cool. I moved the banner to `sitewide_warning.html` It is exactly the same banner as in the image of the description.

**Review by tgrego — APPROVED** [review]
Looks good and informative.
Good spot of the component Mathias!

**Pull request merged**
